comport: COM3
baudrate: 9600
bytesize: 8
parity: N
stopbits: 1
VM: N
VM-Version: banana
Mappings:
  "1":
    ProcessNames: []
    VoiceMeeter: null
    Categories: []
    PluginActions: []
  "2":
    ProcessNames: []
    VoiceMeeter: null
    Categories: []
    PluginActions: []
  "3":
    ProcessNames: []
    VoiceMeeter: null
    Categories: []
    PluginActions: []
  "4":
    ProcessNames: []
    VoiceMeeter: null
    Categories: []
    PluginActions: []
